2024-03-06 15:35:35,963 INFO    MainThread:62788 [internal.py:wandb_internal():90] W&B internal server running at pid: 62788, started at: 2024-03-06 15:35:35.961170
2024-03-06 15:35:35,964 INFO    WriterThread:62788 [datastore.py:open_for_write():75] open: .\wandb\run-20240306_153534-12wvxlkc\run-12wvxlkc.wandb
2024-03-06 15:35:35,967 DEBUG   SenderThread:62788 [sender.py:send():235] send: header
2024-03-06 15:35:35,968 DEBUG   SenderThread:62788 [sender.py:send():235] send: run
2024-03-06 15:35:35,969 INFO    SenderThread:62788 [sender.py:_maybe_setup_resume():492] checking resume status for None/UNet-DAS/12wvxlkc
2024-03-06 15:35:38,714 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: check_version
2024-03-06 15:35:38,721 INFO    SenderThread:62788 [dir_watcher.py:__init__():205] watching files in: .\wandb\run-20240306_153534-12wvxlkc\files
2024-03-06 15:35:38,721 INFO    SenderThread:62788 [sender.py:_start_run_threads():812] run started: 12wvxlkc with start time 1709710534
2024-03-06 15:35:38,721 DEBUG   SenderThread:62788 [sender.py:send():235] send: summary
2024-03-06 15:35:38,722 INFO    SenderThread:62788 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:35:38,722 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: check_version
2024-03-06 15:35:39,600 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: run_start
2024-03-06 15:35:39,628 DEBUG   HandlerThread:62788 [meta.py:__init__():35] meta init
2024-03-06 15:35:39,628 DEBUG   HandlerThread:62788 [meta.py:__init__():49] meta init done
2024-03-06 15:35:39,628 DEBUG   HandlerThread:62788 [meta.py:probe():209] probe
2024-03-06 15:35:39,680 DEBUG   HandlerThread:62788 [meta.py:_setup_git():199] setup git
2024-03-06 15:35:39,733 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_153534-12wvxlkc\files\wandb-summary.json
2024-03-06 15:35:39,799 DEBUG   HandlerThread:62788 [meta.py:_setup_git():206] setup git done
2024-03-06 15:35:39,799 DEBUG   HandlerThread:62788 [meta.py:_save_pip():53] save pip
2024-03-06 15:35:39,800 DEBUG   HandlerThread:62788 [meta.py:_save_pip():67] save pip done
2024-03-06 15:35:39,800 DEBUG   HandlerThread:62788 [meta.py:_save_conda():74] save conda
2024-03-06 15:35:40,742 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_153534-12wvxlkc\files\requirements.txt
2024-03-06 15:35:40,742 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_153534-12wvxlkc\files\conda-environment.yaml
2024-03-06 15:35:42,957 DEBUG   HandlerThread:62788 [meta.py:_save_conda():84] save conda done
2024-03-06 15:35:42,957 DEBUG   HandlerThread:62788 [meta.py:probe():247] probe done
2024-03-06 15:35:43,016 DEBUG   SenderThread:62788 [sender.py:send():235] send: files
2024-03-06 15:35:43,016 INFO    SenderThread:62788 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2024-03-06 15:35:43,016 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:35:43,017 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:35:43,766 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\conda-environment.yaml
2024-03-06 15:35:43,766 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_153534-12wvxlkc\files\wandb-metadata.json
2024-03-06 15:35:43,766 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_153534-12wvxlkc\files\output.log
2024-03-06 15:35:44,247 DEBUG   SenderThread:62788 [sender.py:send():235] send: telemetry
2024-03-06 15:35:44,247 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:35:44,247 DEBUG   SenderThread:62788 [sender.py:send():235] send: telemetry
2024-03-06 15:35:44,248 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:35:44,248 WARNING SenderThread:62788 [sender.py:send_metric():905] Seen metric with glob (shouldn't happen)
2024-03-06 15:35:44,248 DEBUG   SenderThread:62788 [sender.py:send():235] send: config
2024-03-06 15:35:44,951 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:35:44,951 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:35:44,951 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:35:45,780 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\output.log
2024-03-06 15:35:46,614 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:35:46,615 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:35:46,615 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:35:49,639 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:35:49,640 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:35:49,640 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:35:49,640 ERROR   Thread-17 :62788 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 15:35:55,056 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:35:55,056 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:35:55,056 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:35:59,250 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:35:59,250 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:36:03,971 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\output.log
2024-03-06 15:36:04,022 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:04,023 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:36:04,023 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:05,995 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\output.log
2024-03-06 15:36:06,005 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 15:36:06,007 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:36:07,005 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\output.log
2024-03-06 15:36:07,374 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:08,016 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\output.log
2024-03-06 15:36:08,310 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:36:08,311 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:36:08,311 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:36:08,311 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:36:08,311 DEBUG   SenderThread:62788 [sender.py:send():235] send: metric
2024-03-06 15:36:08,311 DEBUG   SenderThread:62788 [sender.py:send():235] send: history
2024-03-06 15:36:08,311 DEBUG   SenderThread:62788 [sender.py:send():235] send: summary
2024-03-06 15:36:08,312 INFO    SenderThread:62788 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:36:08,313 DEBUG   SenderThread:62788 [sender.py:send():235] send: telemetry
2024-03-06 15:36:08,313 DEBUG   SenderThread:62788 [sender.py:send():235] send: exit
2024-03-06 15:36:08,313 INFO    SenderThread:62788 [sender.py:send_exit():371] handling exit code: 0
2024-03-06 15:36:08,313 INFO    SenderThread:62788 [sender.py:send_exit():373] handling runtime: 27
2024-03-06 15:36:08,314 INFO    SenderThread:62788 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:36:08,314 INFO    SenderThread:62788 [sender.py:send_exit():379] send defer
2024-03-06 15:36:08,314 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:08,314 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:08,315 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 0
2024-03-06 15:36:08,315 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:08,315 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 0
2024-03-06 15:36:08,315 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 1
2024-03-06 15:36:08,315 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:08,315 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 1
2024-03-06 15:36:08,481 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:08,481 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:08,482 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 1
2024-03-06 15:36:08,482 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 2
2024-03-06 15:36:08,482 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:08,482 DEBUG   SenderThread:62788 [sender.py:send():235] send: stats
2024-03-06 15:36:08,483 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:08,483 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 2
2024-03-06 15:36:08,483 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:08,483 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 2
2024-03-06 15:36:08,483 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 3
2024-03-06 15:36:08,483 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:08,484 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 3
2024-03-06 15:36:08,484 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:08,484 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 3
2024-03-06 15:36:08,484 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 4
2024-03-06 15:36:08,484 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:08,484 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 4
2024-03-06 15:36:08,484 DEBUG   SenderThread:62788 [sender.py:send():235] send: summary
2024-03-06 15:36:08,485 INFO    SenderThread:62788 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:36:08,496 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:08,496 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 4
2024-03-06 15:36:08,496 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 5
2024-03-06 15:36:08,504 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:08,504 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 5
2024-03-06 15:36:08,505 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:08,505 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 5
2024-03-06 15:36:08,583 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:09,026 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\wandb-summary.json
2024-03-06 15:36:09,027 INFO    Thread-11 :62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\config.yaml
2024-03-06 15:36:09,889 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 6
2024-03-06 15:36:09,890 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:09,890 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:09,890 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 6
2024-03-06 15:36:09,890 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:09,890 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 6
2024-03-06 15:36:09,890 INFO    SenderThread:62788 [dir_watcher.py:finish():336] shutting down directory watcher
2024-03-06 15:36:10,001 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,033 INFO    SenderThread:62788 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_153534-12wvxlkc\files\config.yaml
2024-03-06 15:36:10,033 INFO    SenderThread:62788 [dir_watcher.py:finish():366] scan: .\wandb\run-20240306_153534-12wvxlkc\files
2024-03-06 15:36:10,033 INFO    SenderThread:62788 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_153534-12wvxlkc\files\conda-environment.yaml conda-environment.yaml
2024-03-06 15:36:10,034 INFO    SenderThread:62788 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_153534-12wvxlkc\files\config.yaml config.yaml
2024-03-06 15:36:10,036 INFO    SenderThread:62788 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_153534-12wvxlkc\files\output.log output.log
2024-03-06 15:36:10,039 INFO    SenderThread:62788 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_153534-12wvxlkc\files\requirements.txt requirements.txt
2024-03-06 15:36:10,042 INFO    SenderThread:62788 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_153534-12wvxlkc\files\wandb-metadata.json wandb-metadata.json
2024-03-06 15:36:10,042 INFO    SenderThread:62788 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_153534-12wvxlkc\files\wandb-summary.json wandb-summary.json
2024-03-06 15:36:10,046 INFO    SenderThread:62788 [sender.py:transition_state():392] send defer: 7
2024-03-06 15:36:10,046 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,047 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:36:10,048 INFO    HandlerThread:62788 [handler.py:handle_request_defer():164] handle defer: 7
2024-03-06 15:36:10,049 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: defer
2024-03-06 15:36:10,049 INFO    SenderThread:62788 [sender.py:send_request_defer():388] handle sender defer: 7
2024-03-06 15:36:10,049 INFO    SenderThread:62788 [file_pusher.py:finish():145] shutting down file pusher
2024-03-06 15:36:10,152 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,152 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,261 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,261 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,368 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,368 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,473 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,473 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,581 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,581 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,687 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,687 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,794 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,794 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:10,902 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:10,902 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,009 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,009 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,116 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,116 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,224 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,224 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,331 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,331 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,438 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,438 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,545 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,545 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,651 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,651 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,759 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,759 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,865 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,865 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:11,972 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:11,972 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,081 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,081 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,186 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,186 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,293 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,293 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,399 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,399 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,506 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,506 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,611 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,611 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,719 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,719 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,825 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,825 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:12,932 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:12,932 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,040 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,040 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,148 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,148 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,254 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,254 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,361 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,361 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,470 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,471 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,578 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,578 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,686 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,686 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,792 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,792 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,847 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:13,848 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:36:13,848 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:13,901 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:13,901 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:13,937 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:13,937 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:36:13,937 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:14,005 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:14,005 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:36:14,005 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:14,006 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,006 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,113 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,113 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,219 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,219 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,326 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,326 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,434 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,434 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,541 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,541 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,648 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,648 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,755 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,755 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,863 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,863 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:14,973 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:14,973 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,079 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,079 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,186 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,186 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,292 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,292 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,399 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,399 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,508 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,508 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,593 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:15,593 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:36:15,593 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:15,616 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,616 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,724 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,724 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,730 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:15,730 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:36:15,730 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:15,773 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:15,774 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:36:15,774 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:15,831 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,831 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:15,940 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:15,940 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,047 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,047 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,153 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,153 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,262 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,262 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,367 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,367 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,421 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:16,422 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:36:16,422 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:16,476 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,476 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,583 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,583 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,690 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,690 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,798 DEBUG   HandlerThread:62788 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:36:16,798 DEBUG   SenderThread:62788 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:36:16,835 WARNING MainThread:62788 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-03-06 15:36:16,883 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:16,884 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:36:16,884 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:17,861 WARNING MainThread:62788 [internal.py:is_dead():387] Internal process exiting, parent pid 60812 disappeared
2024-03-06 15:36:17,861 ERROR   MainThread:62788 [internal.py:wandb_internal():149] Internal process shutdown.
2024-03-06 15:36:18,165 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:18,166 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:36:18,166 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:18,605 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:18,605 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:36:18,605 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:18,611 INFO    WriterThread:62788 [datastore.py:close():279] close: .\wandb\run-20240306_153534-12wvxlkc\run-12wvxlkc.wandb
2024-03-06 15:36:18,684 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:18,684 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:36:18,684 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:18,795 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:18,795 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:36:18,795 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:18,824 INFO    SenderThread:62788 [sender.py:finish():1111] shutting down sender
2024-03-06 15:36:18,824 INFO    SenderThread:62788 [file_pusher.py:finish():145] shutting down file pusher
2024-03-06 15:36:18,824 INFO    SenderThread:62788 [file_pusher.py:join():150] waiting for file pusher
2024-03-06 15:36:18,824 INFO    HandlerThread:62788 [handler.py:finish():806] shutting down handler
2024-03-06 15:36:18,825 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:18,825 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:36:18,825 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:21,194 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:21,195 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:36:21,195 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:21,694 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:21,694 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:36:21,694 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:23,571 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:23,571 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:36:23,571 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:23,738 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:23,738 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:36:23,738 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:24,046 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:24,047 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:36:24,047 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:24,150 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:24,150 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:36:24,150 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:26,001 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:26,001 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:36:26,001 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:26,661 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:26,661 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:36:26,661 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:32,594 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:32,594 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:36:32,594 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:32,962 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:32,962 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:36:32,962 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:33,856 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:33,856 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:36:33,856 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:34,738 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:34,738 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:36:34,738 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:37,024 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:37,025 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:36:37,025 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:49,591 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:49,591 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:36:49,591 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:52,802 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:52,802 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:36:52,802 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:52,835 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:52,836 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:36:52,836 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:54,181 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:54,181 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:36:54,181 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:36:56,345 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:36:56,345 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:36:56,345 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:37:00,455 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-metadata.json?Expires=1709796944&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Hy1yiNcuy8O6X2lRfNR%2FX89YM6lzmRLOx0b%2FXWX423RA%2FC%2FTwjuv2hb6m3Boz%2BzT87jMx7FasoJ3B1OH9ida%2BSv6kt0Ql2ZdiLO0ZAHgxFyNN5VUT0%2BnFPkXS5szmS3ydv63EMKWfnfDIGLgklJgS0wvq%2FjU3RRMS%2F6M%2BDDgc3uqw9Y9qBZ3XnEn39aDO7z%2BsDNVD2BVwRNrSLhpKj%2BQYRfzPVa5LpaEjsudjy9s3YnHkLhW%2FpYqDrix0VzSHShyAxo82PjTvBahU2AV5rUPhI%2B4SoI2RwD3qvjN61jDzvx39RnqC8U3BK6f%2F4iTD4AjsxOTa1GpxSiVx9a22050%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:37:00,455 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '889'}
2024-03-06 15:37:00,455 ERROR   Thread-17 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:37:25,881 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:37:25,882 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:37:25,882 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:37:27,103 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:37:27,103 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:37:27,103 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:37:27,716 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:37:27,716 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:37:27,716 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:37:28,080 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:37:28,080 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:37:28,080 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:37:36,440 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:37:36,440 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:37:36,440 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:38:16,011 INFO    Thread-17 :62788 [upload_job.py:push():132] Uploaded file C:\Users\19086\AppData\Local\Temp\tmpwzuducxmwandb\1aitv67a-wandb-metadata.json
2024-03-06 15:38:43,030 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:38:43,030 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:38:43,030 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:38:43,767 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:38:43,767 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:38:43,768 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:38:44,823 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:38:44,823 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:38:44,823 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:38:46,978 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:38:46,978 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:38:46,978 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:38:47,013 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:38:47,013 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:38:47,013 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:40:57,265 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:40:57,266 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:40:57,266 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:41:01,214 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:41:01,214 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:41:01,214 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:41:07,067 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:41:07,067 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:41:07,067 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:41:09,496 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:41:09,496 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:41:09,496 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:41:16,998 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:41:16,998 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:41:16,998 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:46:03,905 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:46:03,906 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:46:03,906 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:46:04,620 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:46:04,620 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:46:04,621 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:46:07,604 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:46:07,604 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:46:07,604 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:46:08,342 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:46:08,342 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:46:08,342 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:46:24,166 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:46:24,167 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:46:24,167 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:51:15,051 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:51:15,051 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:51:15,051 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:51:19,329 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:51:19,329 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:51:19,329 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:52:13,911 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:52:13,911 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:52:13,911 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:52:14,964 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:52:14,964 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:52:14,965 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:52:20,282 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:52:20,282 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:52:20,282 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:56:50,965 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:56:50,966 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 15:56:50,966 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:57:02,345 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:57:02,346 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 15:57:02,346 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:57:15,661 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:57:15,661 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 15:57:15,661 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:57:49,352 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:57:49,352 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 15:57:49,352 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:58:33,965 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:58:33,965 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:58:33,965 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:02:49,142 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:02:49,142 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 16:02:49,142 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:02:52,563 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:02:52,563 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 16:02:52,563 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:03:12,351 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:03:12,351 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 16:03:12,351 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:04:04,837 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/config.yaml?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iA1otg37PME92V5JhYXi4Eh%2BHBmZVxz4p7mEBN9Zah86PZV6Wrxzs0vL4eSfLch9BsOJIAP5tAROLlnEq8DYSbbSaIHIcsadb62CkmJH2NCjeOfzx8xV4zKuL6KslRyAv%2FIloxUcemMbLt4KxrTnYeH5vLOR2Pw38FRNCLzPRV%2FekLGxS%2FR6TGDGG8szf87gSw%2FmPkeRGWRK5zrG4%2FDXJrTt3JfjJ2D2TEZtESCNHSo1EiM16WDo%2Bol%2F8c8%2FT%2F9oBCrL%2Biw5KTEFt2h1xuULZGsQRLBmX%2FHXMHoZdvs%2BEnhoaxLhd%2FoAqY26DIFzFvIRgLaLiJy2MikrTukCm92T%2BA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:04:04,838 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1894'}
2024-03-06 16:04:04,838 ERROR   Thread-19 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:04:42,046 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/requirements.txt?Expires=1709796976&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FONgr%2B6vaRk14nygwcmTrc0niRKBeQelnQz%2FvC2DiftCmEtUhtDjd1LY7wCdoFX3D8XeFsOJ74k%2BL%2B5DRDgPKf2zj25IS22UYTcScVlIfY0oMz5OFoxEQCt%2FRyacDNuTs9eVyqkunjQHcdT7%2B0Oj0p1A6%2Bfywjyxg07wQUxvJOGhIviy3%2FppVBwJ2f5EqoB5k4iliowOCQbAu6cmaaI50F5b6erWlHMg30rwoumIO%2BhxLa7Vc%2BmcScY2Zai3rU9mFZQaiTJKhIeX1qxmxPlxK6Q0aakA%2B9ICt6WDYj2DgbjF95j9r7j4j27e4X3h06zLYGw7J1zZdkW5P4lQgHHc%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:04:42,046 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 16:04:42,046 ERROR   Thread-21 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:08:23,018 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/conda-environment.yaml?Expires=1709796975&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jP8UcnohNotTS5Jd6njWNZ%2F12ygn3LQec9VWG%2BcCeJh6aEKNPS1i5OvdMXaco%2FiEvv%2FCS5%2Fa%2FdSda5%2FQm2QUkFXt6Nzrj9%2B%2FAKsvx%2FuV8kmfMSKjqcPGAik5Q%2BUkOSTxC4wRBIQjGyJGAg08OwOH22NYCPcbDb7Q%2FaCs8HYNrOvJk0B99e4ixB12hq6Z5IUHAovzmvAwJxz5UlJDY7bfql3O1V5DRUFX%2FGYUKw5Wjy2zZE5DD8d2Y5Xe4fDR6YdJEwhQJCX%2BV1MMc4AUBmBCoSeLBkZ3v6ympv0ItCRHP6dkJOXswYsLhTUsEl3h3NFgF%2BTmlNPzh3gzZnBKbznP2g%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:08:23,018 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 16:08:23,018 ERROR   Thread-18 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:08:34,882 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/wandb-summary.json?Expires=1709796973&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Ir5HxafOMp2S9rcX9BksbIPSETwOIctBabkvkVOsU2UaQ8ZhryO0MpXtx6W6172gJ2Kp43KZZ0rfmW4geaV%2BakRZLhGXFvXDpeaD%2BwGEH%2BSNoeqCoRTV5V8mEoTNmKB7CpH4C6xqCAQov30hOwtHUVgP0fEgDAmnbI0VmhBR0u5aa%2F9Ga4D07%2BxpxzIEHxlqw4jBy49CZhYC%2BJrR0KNv8hYn7UMr6Vsw3wNY32cxZfEDYNUtu0hsVeHNlnImTFrdVTX5rCtRDHxiQzxLdceqGiMnhtAptGCWEAY0uk9Mehjoh2M%2Fb6KsNWhQRkBInsM6Zu9%2B7a4XZzFh4LUC6U0kcw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:08:34,882 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290'}
2024-03-06 16:08:34,882 ERROR   Thread-22 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 16:08:59,072 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/12wvxlkc/output.log?Expires=1709796972&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v25EdGTXE8HFjbua%2FoiN2WwHRZzD7I9%2BB4qIM6qySVoO0wsFuKKKcRFcaH8Ea2bzxrV80oLMXGrDc5BO7ZqsYHfz8y4HziUSwGdAkZY3WdlqcZqgNgco9IBZuqZvWzgDCtqRyZuMM9GPlGSaatFxKIjARgDjer4i2MmfDnltU%2FPtjZK3Psei1Hufuw3vpMsYsUfmnC6jvocu%2BwSNR9TVgLt6EXHyh93P74vm5WjIHkX%2FqKc1ukUQTKgLyc0JtzIC3Q3Q9rP8ZijxWVfl7rAOz9Tmb%2FXXZAtCDRfTNgJHoxI7ce2do73UxjMKDDZLmGPVsaF%2FOg7BSgui0dMsRzYO5Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 16:08:59,072 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2396'}
2024-03-06 16:08:59,073 ERROR   Thread-20 :62788 [internal_api.py:upload_file():1644] upload_file response body: 
