2024-03-06 17:28:43,864 INFO    MainThread:75268 [internal.py:wandb_internal():90] W&B internal server running at pid: 75268, started at: 2024-03-06 17:28:43.864254
2024-03-06 17:28:43,866 INFO    WriterThread:75268 [datastore.py:open_for_write():75] open: .\wandb\run-20240306_172842-220oxg9k\run-220oxg9k.wandb
2024-03-06 17:28:43,869 DEBUG   SenderThread:75268 [sender.py:send():235] send: header
2024-03-06 17:28:43,869 DEBUG   SenderThread:75268 [sender.py:send():235] send: run
2024-03-06 17:28:43,871 INFO    SenderThread:75268 [sender.py:_maybe_setup_resume():492] checking resume status for None/UNet-DAS/220oxg9k
2024-03-06 17:28:46,359 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: check_version
2024-03-06 17:28:46,366 INFO    SenderThread:75268 [dir_watcher.py:__init__():205] watching files in: .\wandb\run-20240306_172842-220oxg9k\files
2024-03-06 17:28:46,367 INFO    SenderThread:75268 [sender.py:_start_run_threads():812] run started: 220oxg9k with start time 1709717322
2024-03-06 17:28:46,367 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:28:46,367 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:28:46,367 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: check_version
2024-03-06 17:28:47,299 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: run_start
2024-03-06 17:28:47,328 DEBUG   HandlerThread:75268 [meta.py:__init__():35] meta init
2024-03-06 17:28:47,328 DEBUG   HandlerThread:75268 [meta.py:__init__():49] meta init done
2024-03-06 17:28:47,328 DEBUG   HandlerThread:75268 [meta.py:probe():209] probe
2024-03-06 17:28:47,383 DEBUG   HandlerThread:75268 [meta.py:_setup_git():199] setup git
2024-03-06 17:28:47,384 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:28:47,529 DEBUG   HandlerThread:75268 [meta.py:_setup_git():206] setup git done
2024-03-06 17:28:47,530 DEBUG   HandlerThread:75268 [meta.py:_save_pip():53] save pip
2024-03-06 17:28:47,530 DEBUG   HandlerThread:75268 [meta.py:_save_pip():67] save pip done
2024-03-06 17:28:47,531 DEBUG   HandlerThread:75268 [meta.py:_save_conda():74] save conda
2024-03-06 17:28:48,387 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_172842-220oxg9k\files\conda-environment.yaml
2024-03-06 17:28:48,387 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_172842-220oxg9k\files\requirements.txt
2024-03-06 17:28:50,575 DEBUG   HandlerThread:75268 [meta.py:_save_conda():84] save conda done
2024-03-06 17:28:50,575 DEBUG   HandlerThread:75268 [meta.py:probe():247] probe done
2024-03-06 17:28:50,628 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:28:50,628 DEBUG   SenderThread:75268 [sender.py:send():235] send: files
2024-03-06 17:28:50,628 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2024-03-06 17:28:50,629 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:28:51,406 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\conda-environment.yaml
2024-03-06 17:28:51,407 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_172842-220oxg9k\files\wandb-metadata.json
2024-03-06 17:28:51,407 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:28:51,989 DEBUG   SenderThread:75268 [sender.py:send():235] send: telemetry
2024-03-06 17:28:51,989 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:28:51,989 DEBUG   SenderThread:75268 [sender.py:send():235] send: telemetry
2024-03-06 17:28:51,989 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:28:51,990 WARNING SenderThread:75268 [sender.py:send_metric():905] Seen metric with glob (shouldn't happen)
2024-03-06 17:28:51,990 DEBUG   SenderThread:75268 [sender.py:send():235] send: config
2024-03-06 17:28:52,448 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:28:52,448 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:28:52,448 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:28:53,416 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:28:54,142 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:28:54,142 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:28:54,142 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:28:56,977 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:28:56,977 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:28:56,977 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:28:56,977 ERROR   Thread-17 :75268 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 17:29:02,038 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:29:02,038 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:29:02,038 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:29:06,990 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:29:06,990 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:29:12,342 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:29:12,343 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:29:12,343 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:29:13,591 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:15,604 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\config.yaml
2024-03-06 17:29:18,378 DEBUG   SenderThread:75268 [sender.py:send():235] send: stats
2024-03-06 17:29:23,319 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:29:23,319 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:29:30,040 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:29:30,040 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:29:30,040 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:29:32,788 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:34,807 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:36,821 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:38,837 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:39,524 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:29:39,525 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:29:40,855 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:42,865 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:44,885 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:46,428 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,430 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:29:46,431 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:29:46,431 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:29:46,447 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:29:46,448 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,448 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,449 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:29:46,449 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:29:46,449 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:29:46,449 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:29:46,900 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:29:46,900 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:48,917 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:50,941 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:51,608 DEBUG   SenderThread:75268 [sender.py:send():235] send: stats
2024-03-06 17:29:52,968 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:54,989 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:56,136 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:29:56,136 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:29:57,005 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:29:59,026 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:00,414 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:00,415 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:00,416 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:00,416 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:00,417 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:00,417 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:00,417 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:00,459 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:01,039 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:30:01,039 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:03,063 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:05,088 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:07,115 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:08,422 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:30:08,423 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:30:08,423 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:30:09,136 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:11,150 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:12,388 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:30:12,388 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:30:13,169 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:14,525 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:14,525 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:14,526 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:14,526 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:14,529 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:14,529 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:14,530 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:14,530 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:15,185 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:30:15,186 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:17,199 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:18,204 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\config.yaml
2024-03-06 17:30:19,211 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:21,226 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:23,233 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:24,737 DEBUG   SenderThread:75268 [sender.py:send():235] send: stats
2024-03-06 17:30:25,255 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:27,270 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:28,717 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:30:28,718 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:30:28,727 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:28,731 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:29,284 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:30,155 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:30,156 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:30,156 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:30,157 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:30,157 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:30,157 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:30,286 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:30:31,301 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:33,314 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:35,341 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:37,360 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:39,371 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:41,389 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:43,166 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:43,167 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:43,167 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:43,168 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:43,170 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:30:43,171 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:30:43,171 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:30:43,172 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:30:43,402 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:30:43,403 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:44,626 DEBUG   SenderThread:75268 [sender.py:send():235] send: config
2024-03-06 17:30:45,169 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:30:45,169 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:30:45,416 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:30:51,474 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\config.yaml
2024-03-06 17:30:57,844 DEBUG   SenderThread:75268 [sender.py:send():235] send: stats
2024-03-06 17:31:02,179 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:31:02,179 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:31:07,616 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:31:08,145 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: partial_history
2024-03-06 17:31:08,146 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:31:08,146 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:31:08,147 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:31:08,147 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:31:08,147 DEBUG   SenderThread:75268 [sender.py:send():235] send: metric
2024-03-06 17:31:08,147 DEBUG   SenderThread:75268 [sender.py:send():235] send: history
2024-03-06 17:31:08,147 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:31:08,149 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:31:08,626 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:31:08,830 DEBUG   SenderThread:75268 [sender.py:send():235] send: telemetry
2024-03-06 17:31:09,010 DEBUG   SenderThread:75268 [sender.py:send():235] send: exit
2024-03-06 17:31:09,010 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:09,010 INFO    SenderThread:75268 [sender.py:send_exit():371] handling exit code: 0
2024-03-06 17:31:09,011 INFO    SenderThread:75268 [sender.py:send_exit():373] handling runtime: 141
2024-03-06 17:31:09,011 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:31:09,011 INFO    SenderThread:75268 [sender.py:send_exit():379] send defer
2024-03-06 17:31:09,012 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:09,012 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:09,012 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 0
2024-03-06 17:31:09,012 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:09,012 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 0
2024-03-06 17:31:09,012 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 1
2024-03-06 17:31:09,013 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:09,013 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 1
2024-03-06 17:31:09,131 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:09,131 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:09,131 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 1
2024-03-06 17:31:09,131 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 2
2024-03-06 17:31:09,131 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:09,132 DEBUG   SenderThread:75268 [sender.py:send():235] send: stats
2024-03-06 17:31:09,132 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:09,132 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 2
2024-03-06 17:31:09,132 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:09,132 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 2
2024-03-06 17:31:09,132 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 3
2024-03-06 17:31:09,133 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:09,133 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 3
2024-03-06 17:31:09,133 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:09,133 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 3
2024-03-06 17:31:09,133 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 4
2024-03-06 17:31:09,133 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:09,133 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 4
2024-03-06 17:31:09,133 DEBUG   SenderThread:75268 [sender.py:send():235] send: summary
2024-03-06 17:31:09,134 INFO    SenderThread:75268 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:31:09,134 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:09,134 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 4
2024-03-06 17:31:09,134 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 5
2024-03-06 17:31:09,135 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:09,135 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 5
2024-03-06 17:31:09,135 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:09,135 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 5
2024-03-06 17:31:09,238 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:09,631 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json
2024-03-06 17:31:09,631 INFO    Thread-11 :75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\output.log
2024-03-06 17:31:12,007 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 6
2024-03-06 17:31:12,007 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:12,007 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:12,008 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 6
2024-03-06 17:31:12,008 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:12,008 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 6
2024-03-06 17:31:12,008 INFO    SenderThread:75268 [dir_watcher.py:finish():336] shutting down directory watcher
2024-03-06 17:31:12,115 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:12,647 INFO    SenderThread:75268 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_172842-220oxg9k\files\config.yaml
2024-03-06 17:31:12,647 INFO    SenderThread:75268 [dir_watcher.py:finish():366] scan: .\wandb\run-20240306_172842-220oxg9k\files
2024-03-06 17:31:12,647 INFO    SenderThread:75268 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_172842-220oxg9k\files\conda-environment.yaml conda-environment.yaml
2024-03-06 17:31:12,648 INFO    SenderThread:75268 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_172842-220oxg9k\files\config.yaml config.yaml
2024-03-06 17:31:12,651 INFO    SenderThread:75268 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_172842-220oxg9k\files\output.log output.log
2024-03-06 17:31:12,653 INFO    SenderThread:75268 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_172842-220oxg9k\files\requirements.txt requirements.txt
2024-03-06 17:31:12,656 INFO    SenderThread:75268 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_172842-220oxg9k\files\wandb-metadata.json wandb-metadata.json
2024-03-06 17:31:12,656 INFO    SenderThread:75268 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_172842-220oxg9k\files\wandb-summary.json wandb-summary.json
2024-03-06 17:31:12,659 INFO    SenderThread:75268 [sender.py:transition_state():392] send defer: 7
2024-03-06 17:31:12,660 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:12,663 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:31:12,663 INFO    HandlerThread:75268 [handler.py:handle_request_defer():164] handle defer: 7
2024-03-06 17:31:12,663 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: defer
2024-03-06 17:31:12,663 INFO    SenderThread:75268 [sender.py:send_request_defer():388] handle sender defer: 7
2024-03-06 17:31:12,663 INFO    SenderThread:75268 [file_pusher.py:finish():145] shutting down file pusher
2024-03-06 17:31:12,766 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:12,766 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:12,873 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:12,873 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:12,982 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:12,982 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,090 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,090 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,195 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,195 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,302 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,302 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,409 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,409 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,515 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,515 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,622 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,622 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,731 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,731 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,839 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,839 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:13,945 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:13,945 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,052 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,054 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,158 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,158 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,263 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,263 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,370 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,370 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,478 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,478 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,586 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,586 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,606 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:14,606 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:31:14,606 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:14,630 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:14,631 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:31:14,631 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:14,682 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:14,682 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:31:14,682 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:14,695 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,695 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,730 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:14,730 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:31:14,730 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:14,761 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:14,762 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:31:14,762 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:14,803 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,803 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:14,909 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:14,909 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,017 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,017 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,124 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,124 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,230 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,230 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,340 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,340 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,448 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,448 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,554 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,554 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,661 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,661 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,767 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,767 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,875 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,875 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:15,982 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:15,982 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,091 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,091 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,198 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,198 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,238 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:16,239 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:31:16,239 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:16,303 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,303 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,413 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,413 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,417 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:16,417 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:31:16,417 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:16,421 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:16,421 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:31:16,421 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:16,469 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:16,469 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:31:16,469 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:16,520 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,520 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,583 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:16,584 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:31:16,584 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:16,628 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,628 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,736 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,736 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,843 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,843 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:16,951 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:16,952 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,059 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,059 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,165 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,165 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,179 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:17,179 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:31:17,179 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:17,274 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,274 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,381 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,381 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,488 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,488 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,593 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,593 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,699 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,699 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,807 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,807 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:17,914 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:17,914 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,022 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,022 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,128 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,128 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,235 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,236 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,343 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,343 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,451 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,451 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,556 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,556 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,665 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,665 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,771 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,771 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,878 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,878 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:18,989 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:18,989 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:19,099 DEBUG   HandlerThread:75268 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:31:19,099 DEBUG   SenderThread:75268 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:31:19,130 WARNING MainThread:75268 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-03-06 17:31:19,295 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:19,296 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:31:19,296 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:19,314 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:19,314 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:31:19,314 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:19,397 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:19,397 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:31:19,397 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:19,498 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:19,499 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:31:19,499 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:19,576 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:19,576 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:31:19,576 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:24,028 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:24,029 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:31:24,029 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:24,737 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:24,737 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:31:24,737 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:24,752 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:24,752 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:31:24,752 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:24,828 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:24,828 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:31:24,828 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:25,115 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:25,115 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:31:25,115 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:26,193 WARNING MainThread:75268 [internal.py:is_dead():387] Internal process exiting, parent pid 68472 disappeared
2024-03-06 17:31:26,193 ERROR   MainThread:75268 [internal.py:wandb_internal():149] Internal process shutdown.
2024-03-06 17:31:26,249 INFO    WriterThread:75268 [datastore.py:close():279] close: .\wandb\run-20240306_172842-220oxg9k\run-220oxg9k.wandb
2024-03-06 17:31:27,152 INFO    SenderThread:75268 [sender.py:finish():1111] shutting down sender
2024-03-06 17:31:27,152 INFO    SenderThread:75268 [file_pusher.py:finish():145] shutting down file pusher
2024-03-06 17:31:27,152 INFO    SenderThread:75268 [file_pusher.py:join():150] waiting for file pusher
2024-03-06 17:31:27,152 INFO    HandlerThread:75268 [handler.py:finish():806] shutting down handler
2024-03-06 17:31:33,537 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:33,538 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:31:33,538 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:33,944 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:33,944 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:31:33,944 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:35,030 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:35,030 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:31:35,031 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:35,246 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:35,246 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:31:35,246 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:35,413 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:35,413 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:31:35,413 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:51,121 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:51,121 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:31:51,121 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:51,156 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:51,156 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:31:51,156 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:52,693 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:52,693 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:31:52,693 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:53,726 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:53,726 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:31:53,726 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:31:54,532 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:31:54,532 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:31:54,532 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:32:26,521 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:32:26,521 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:32:26,521 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:32:26,804 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:32:26,804 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:32:26,804 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:32:28,279 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:32:28,279 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:32:28,279 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:32:28,759 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:32:28,759 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:32:28,759 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:32:29,292 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:32:29,292 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:32:29,292 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:33:31,571 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:33:31,572 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:33:31,572 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:33:35,689 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:33:35,689 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:33:35,689 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:33:35,710 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:33:35,710 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:33:35,710 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:33:36,527 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:33:36,527 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:33:36,527 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:33:43,675 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:33:43,675 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:33:43,675 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:33:52,939 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:33:52,940 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:33:52,940 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:35:53,455 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:35:53,455 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:35:53,455 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:35:54,480 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:35:54,480 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:35:54,480 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:35:59,353 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:35:59,354 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:35:59,354 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:36:00,011 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:36:00,011 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:36:00,011 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:36:10,403 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:36:10,403 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:36:10,403 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:38:39,649 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:38:39,649 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:38:39,649 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:40:15,260 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:40:15,266 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:40:15,266 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:40:38,082 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:40:38,082 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:40:38,082 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:40:40,010 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:40:40,011 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:40:40,011 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:40:42,913 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:40:42,913 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:40:42,913 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:41:17,181 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:41:17,181 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:41:17,181 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:44:10,213 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:44:10,214 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:44:10,214 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:45:49,675 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:45:49,675 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:45:49,675 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:45:59,384 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:45:59,384 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:45:59,384 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:46:29,105 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:46:29,106 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:46:29,106 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:46:33,165 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:46:33,165 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:46:33,165 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:47:10,546 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:47:10,546 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:47:10,547 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:49:42,850 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:49:42,850 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:49:42,850 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:51:25,142 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:51:25,143 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:51:25,143 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:51:43,681 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:51:43,681 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:51:43,681 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:51:53,283 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:51:53,283 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:51:53,285 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:52:10,163 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:52:10,163 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:52:10,163 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:52:59,765 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:52:59,765 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:52:59,765 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:55:41,342 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:55:41,342 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 17:55:41,342 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:56:46,753 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:56:46,753 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 17:56:46,754 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:56:57,228 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:56:57,228 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 17:56:57,229 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:57:47,017 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/conda-environment.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=MKKCz0VV1B%2BiVQ3pStOEN1uTQJ3QJ5fj1ccWTNsj0d0z%2F28sdXNcbXwOpnK%2BsZa8fp%2BwMJ%2FjSBUgbwICWlOrpjJqC55jn0J%2BnI2HUjSfgZ7uziS2vPPOUttGRh7g737nZPqhRCetVJ6u5q%2F9s%2Br75IGvBUPcDcF%2ByVtJzC08Zqf%2FP9YBIvI3uOte8HEuc6BTCug%2BWj57wiCC5iix%2BdkMHw4gQW%2FV6qsqv1tuLHTxqfpTfQZFhCXYPthgjKxDEgsCRUOykcu185538IoPNCkKrsHD%2F9AyBl6gc9Y%2Fdqi4%2FGpEq%2BKq9uQEHHM8g2c%2BQEkRHQaapi1Dw1KWC%2FyqnjQ5sw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:57:47,017 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1975'}
2024-03-06 17:57:47,017 ERROR   Thread-18 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:57:53,559 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:57:53,559 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 17:57:53,559 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:58:31,983 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:58:31,983 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 17:58:31,983 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 18:01:38,679 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-metadata.json?Expires=1709803732&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KTgE8JgIXaK5LwL1P8qC61Fgj%2FHZOvCAOJERkX7X4LiVmV9JdR9egpL5X6%2B8FhWl5gC9dEAwZEgG7bSdvinT9ohecqxaavNWVZkz%2BQ0yrx1tsr9wtex%2BzUtXDQPHVpKV5dfukErzXjaBsXBoZfyTUZXS9rzCFqz2gUPhyRlK0A61AJfq8mx6AUB3SClMznehNaSO8YiXyVCcIEdg0cl%2FqnV5p7NUhwP%2Bb09l0%2FMbls1m6tkpTcQhhtQ327Zuwq0BNYVK9HGX%2FpcmdcG2y0TCs1%2BeLJFQKZhwb2PgPouCm3eeStTnGr90qRXNY15g%2FZfuJ9Sh38YTctQ5aBeXvx8Q0A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 18:01:38,679 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '967'}
2024-03-06 18:01:38,679 ERROR   Thread-17 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 18:02:38,470 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/wandb-summary.json?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BlDlGMQfBoxyRMzZfyb5pdSN4y0fjRBBmcuFmg9wKWLRv7agLOM8xQ7JaRle0ZQ%2Fvzwm22trwvb5EmBUxwAGhikLOVn7P%2FYecnz8t0pMstP%2Fkj3QqWOc8ed%2FW2XHSeTp1oqBdiUY4TN4HHfnIwHDfAHeXzMbNBdla%2FMiM4R%2F99Ahpgi9PWTBBrEaEgSOCAR1YTotoUivJSJFHmLaCV1%2BNPOojSMyqouHWkPRGBa8vh5gwlxCogRbw%2BuFamLIB6tl1BxOk7MFvRPTZKG3m8pgkXJ4uHIRv4jtnFcppuiOpdnffrNOp68y2IGSEc70rmo4oqUQsjHLsJLIIgwpH4%2BGRg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 18:02:38,470 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '577'}
2024-03-06 18:02:38,470 ERROR   Thread-22 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 18:02:46,570 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/output.log?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jyRYyxM8i%2BjNi8QkFM6QwORkHV%2B47DtYkGBbpOimjtVBcoWnrJtAyv0oFJGjBbQt42hv2C5wCqe%2B9j4LCC%2FW3RNqJHWvUGpGmNb4EUOYvshMQ5eZO%2BZMOHhXNbq0kDIopDHKoTJ5oJxmPJjlJDvbpIKJKyyw2Razv5xQ6N%2BVahIRp3RpQvEpMJZFYOU6u6fBuFjZpQE%2B3JYOjEcs%2F5B3j9WahlIZHrkTnn2h5DAEBamXIChiL5BcVaAxmPDfSDGttoCidIwihwkJHtLj8jmY5I%2Ffz183upxWhSBJjNx9nZxAXPpAezTmgoGv%2BKYqRjXzCJ71aWVqMgDZvaCVIGYqgw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 18:02:46,571 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4712'}
2024-03-06 18:02:46,571 ERROR   Thread-20 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 18:03:01,231 INFO    Thread-18 :75268 [upload_job.py:push():132] Uploaded file .\wandb\run-20240306_172842-220oxg9k\files\conda-environment.yaml
2024-03-06 18:03:39,883 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/config.yaml?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KDyIlXpU1ckQE7M3nqqzYYA39oXXt7JLFBF0cAT3bSG1mTQriX5A1S%2BA1Z6rC4m28EhVIsjYN6y5iezvPeIYOKr9%2FwZ%2BaESx%2BHqkS1NWZV%2BF4NnWAl6XFB2xmTl1oXbO7TxWfGsdiS4xeImrlkZFevGOamqU15nXwXYQ89E1Ej9F%2B6LZ18dLK99LydJUDYR3YYnMK0ACHnhKSI1Kr9fYfKrLJyflEbVGuoY6ycd%2BpZS3W67sefV7r7set5GMZEBP2TrWoxgpWfjQs86oTAOlSO8PtwrOU5Lo7gYANRJQ%2FOXHpktYcZQwoQ5ImVwEIPkEls%2FaAOWyX2WAxn0BnhmJDg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 18:03:39,884 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2317'}
2024-03-06 18:03:39,884 ERROR   Thread-19 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 18:04:29,658 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/220oxg9k/requirements.txt?Expires=1709803874&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A6EbAf6kXtDHo75V09Vqrc3qThurVguxXqDOtD1nLx2zS71L%2Bn%2FmUzxm1g97693lUvYX0bwX4CrIHtoaXo41IYsUKJ2RLQu%2FzS%2FurAAAIF4NydWDk2OeZS%2FkvGamsrA3%2F6eMSn5kHpW0G1AsZbTdr1BOY1wB25US3mItMhaKU1kuz8MyO6t0kSUZN3QGZSV9dwlLAXvrKRT7%2BxXgi%2FEbK%2BXp6ABwyW1AtulldXPjkkUhgwIx0XkC5LvZIfEG9D4Jlc%2FVDF52U3Ep4PWSKnd5Uyj6Rk8WVd3E1MHbr2iwIiBYos0HlFqK5%2FtxNniSWba0FKeaE1WGjcDEa2h7a1Ll%2Bg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 18:04:29,658 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 18:04:29,658 ERROR   Thread-21 :75268 [internal_api.py:upload_file():1644] upload_file response body: 
