2024-03-06 17:26:39,672 INFO    MainThread:66884 [wandb_setup.py:_flush():76] Loading settings from C:\Users\19086\.config\wandb\settings
2024-03-06 17:26:39,672 INFO    MainThread:66884 [wandb_setup.py:_flush():76] Loading settings from D:\HISLab\±œ…Ë\CODE\wandb\settings
2024-03-06 17:26:39,672 INFO    MainThread:66884 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-06 17:26:39,672 INFO    MainThread:66884 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2024-03-06 17:26:39,673 INFO    MainThread:66884 [wandb_init.py:_log_setup():428] Logging user logs to .\wandb\run-20240306_172639-audi6kob\logs\debug.log
2024-03-06 17:26:39,673 INFO    MainThread:66884 [wandb_init.py:_log_setup():429] Logging internal logs to .\wandb\run-20240306_172639-audi6kob\logs\debug-internal.log
2024-03-06 17:26:39,674 INFO    MainThread:66884 [wandb_init.py:init():462] calling init triggers
2024-03-06 17:26:39,674 INFO    MainThread:66884 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2024-03-06 17:26:39,675 INFO    MainThread:66884 [wandb_init.py:init():515] starting backend
2024-03-06 17:26:39,675 INFO    MainThread:66884 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2024-03-06 17:26:39,679 INFO    MainThread:66884 [backend.py:ensure_launched():217] starting backend process...
2024-03-06 17:26:39,762 INFO    MainThread:66884 [backend.py:ensure_launched():222] started backend process with pid: 71920
2024-03-06 17:26:39,763 INFO    MainThread:66884 [wandb_init.py:init():525] backend started and connected
2024-03-06 17:26:39,767 INFO    MainThread:66884 [wandb_init.py:init():596] updated telemetry
2024-03-06 17:26:39,836 INFO    MainThread:66884 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2024-03-06 17:27:09,839 INFO    MainThread:66884 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2024-03-06 17:27:09,839 ERROR   MainThread:66884 [wandb_init.py:init():636] backend process timed out
2024-03-06 17:27:09,839 ERROR   MainThread:66884 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
